framework:
    workflows:
        task_workflow:
            type: 'state_machine'
            supports:
                - App\Entity\Task
            initial_marking: 'pending'
            places:
                - pending
                - in_progress
                - completed
            transitions:
                start:
                    from: pending
                    to: in_progress
                complete:
                    from: in_progress
                    to: completed
